plugins {
    id "com.android.application"
}

android {
    namespace "com.stuart.smartmirror"
    compileSdk 34

    defaultConfig {
        applicationId "com.stuart.smartmirror"
        minSdk 25
        targetSdk 25
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
